[package]
name = "gateway"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.12"
chrono = { version = "0.4.24", features = ["serde"] }
dotenv = "0.15.0"
itertools = "0.10.5"
serde = "1.0.159"
tokio = { version = "1.27.0", features = ["rt-multi-thread"] }
utoipa = "3.2.1"

[features]
query-debug = []
