with open("../schemas/AggregatesItem.avsc") as f:
  content = ' '.join(f.readlines())
  content = content.replace('\n', ' ')
  content = content.replace('\t', '')
  content = content.replace('"', '\\"')
  content = content.replace(' ', '')
  content = content.replace(',', ', ')
  content = content.replace(':', ': ')
  content = content.replace('{', '{ ')
  content = content.replace('[', '[ ')
  content = content.replace('}', ' }')
  content = content.replace(']', ' ]')
  print(content)
print("\n\n")
with open("../schemas/AggregatesPrice.avsc") as f:
  content = ' '.join(f.readlines())
  content = content.replace('\n', ' ')
  content = content.replace('\t', '')
  content = content.replace('"', '\\"')
  content = content.replace(' ', '')
  content = content.replace(',', ', ')
  content = content.replace(':', ': ')
  content = content.replace('{', '{ ')
  content = content.replace('[', '[ ')
  content = content.replace('}', ' }')
  content = content.replace(']', ' ]')
  print(content)